environment: test
debug: true

port: 3545

trace:
  type: ''
  endpoint: ''

redis:
  host: redis-server:6379
  # password: redispass
  db: 0

openAI:
  endpoint: ''
  token: ''

elasticSearch:
  address:
    - "http://es:9200"

miluvs:
  endpoint: milvus-standalone:19530
  username: minioadmin
  password: minioadmin
  db: test

forceRebuild: false